[project]
name = "parse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "ollama>=0.5.1",
    "pdfplumber>=0.11.7",
    "requests>=2.32.4",
]
